<a href="https://colab.research.google.com/github/gulshan0201/Soft_computing-/blob/main/Softcomputing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Perceptron for AND gate

In [3]:
import numpy as np
# AND gate dataset
x= np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
y = np.array([0, 0, 0, 1])
# Initialize weights and bias
w = np.array([0.2, -0.1])
b = 0.0

eta = 0.1
epochs = 5

def step(x):
    return 1 if x >= 0 else 0

errors_per_epoch = []

# Training
for epoch in range(epochs):
    total_error = 0

    for i in range(len(x)):
        summation = np.dot(w, x[i]) + b
        activation= step(summation)
        error = y[i] -activation

        # Update weights and bias
        w = w + eta * error * x[i]
        b = b + eta * error

        total_error +=int(error!=0)

    errors_per_epoch.append(total_error)

# Final predictions
predictions = []
for i in range(len(x)):
    net = np.dot(w, x[i]) + b
    predictions.append(step(net))

predictions = np.array(predictions)

# Printing required output
print("Errors in each epochs :", errors_per_epoch)
print("after all the epochs final Weights:", w)
print("after all the epochs final Bias:", b)
print("after all the epochs final Predictions:", predictions)

Errors in each epochs : [3, 2, 3, 0, 0]
after all the epochs final Weights: [0.2 0.1]
after all the epochs final Bias: -0.20000000000000004
after all the epochs final Predictions: [0 0 0 1]

# Fuzzyset operations

In [8]:
def fuzzy_union(A, B):
    union_set = {}
    for element in A.keys():
        union_set[element] = max(A[element], B[element])
    return union_set

In [7]:

def fuzzy_intersection(A, B):
    intersection_set = {}
    for element in A.keys():
        intersection_set[element] = min(A[element], B[element])
    return intersection_set

In [6]:

def fuzzy_complement(A):
    complement_set = {}
    for element, membership in A.items():
        complement_set[element] = 1.0 - membership
    return complement_set

In [10]:
def fuzzy_difference(A, B):
    complement_B = fuzzy_complement(B)
    return fuzzy_intersection(A,complement_B)

In [14]:
A = {
    'x1': 0.8,
    'x2': 0.3,
    'x3': 0.7
}

B = {
    'x1': 0.6,
    'x2': 0.9,
    'x3': 0.2
}

print("Fuzzy Set A:", A)
print("Fuzzy Set B:", B)

Fuzzy Set A: {'x1': 0.8, 'x2': 0.3, 'x3': 0.7}
Fuzzy Set B: {'x1': 0.6, 'x2': 0.9, 'x3': 0.2}

In [15]:
print("\n-- Operations --")

# 1) Union
union_AB = fuzzy_union(A, B)
print(" Union (A U B):", union_AB)

# 2) Intersection
intersection_AB = fuzzy_intersection(A, B)
print(" Intersection (A intersect B):", intersection_AB)

# 3) Complement (A')
complement_A = fuzzy_complement(A)
print(" Complement of A (A'):", complement_A)

# 4) Set Difference (A - B)
difference_AB = fuzzy_difference(A, B)
print(" Set Difference (A - B):", difference_AB)

-- Operations --
 Union (A U B): {'x1': 0.8, 'x2': 0.9, 'x3': 0.7}
 Intersection (A intersect B): {'x1': 0.6, 'x2': 0.3, 'x3': 0.2}
 Complement of A (A'): {'x1': 0.19999999999999996, 'x2': 0.7, 'x3': 0.30000000000000004}
 Set Difference (A - B): {'x1': 0.4, 'x2': 0.09999999999999998, 'x3': 0.7}

# Fuzzy relation

In [12]:
import pandas as pd

def fuzzy_relation(A, B):
    rows = list(A.keys())
    columns = list(B.keys())
    df = pd.DataFrame(index=rows, columns=columns)

    # Fill the matrix using min operation
    for a in rows:
        for b in columns:
            df.loc[a, b] = min(A[a], B[b])

    return df


A = {'a1': 0.2, 'a2': 0.7, 'a3': 0.4}
B = {'b1': 0.5, 'b2': 0.6}

relation = fuzzy_relation(A, B)
display(relation)
print()
import pandas as pd

def max_min_composition(R, S):
    X = R.index
    Y = R.columns
    Z = S.columns
    T = pd.DataFrame( index=X, columns=Z)

    # Max–Min composition
    for x in X:
        for z in Z:
            T.loc[x, z] = max(
                min(R.loc[x, y], S.loc[y, z]) for y in Y
            )

    return T



# R: X → Y
R = pd.DataFrame(
    [[0.2, 0.7],
     [0.5, 0.4]],
    index=['x1', 'x2'],
    columns=['y1', 'y2']
)

# S: Y → Z
S = pd.DataFrame(
    [[0.6, 0.3],
     [0.8, 0.5]],
    index=['y1', 'y2'],
    columns=['z1', 'z2']
)

T = max_min_composition(R, S)
display(T)

     b1   b2
a1  0.2  0.2
a2  0.5  0.6
a3  0.4  0.4

     z1   z2
x1  0.7  0.5
x2  0.5  0.4